---
  env: 
    es6: true
    commonjs: true
    browser: true
  extends: "eslint:recommended"
  installedESLint: true
  parserOptions: 
    ecmaFeatures: 
      experimentalObjectRestSpread: true
      jsx: true
    sourceType: "module"
  plugins: 
    - "react"
  rules: 
    comma-dangle: 0
    no-console: 1
    no-unused-vars: 1
    semi: 1
    linebreak-style: 1
    eol-last: 1
    indent: 1
    no-trailing-spaces: 1
    key-spacing: 1
    space-before-blocks: 1
